theme: jekyll-theme-monophase
title: Deborah Plana
description: MD-PhD Candidate at Harvard Medical School and MIT

# Google Analytics
ga_tracking: G-D6XE4FKZ4T
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings
